services:

  db:
    image: docker.io/postgres:15.2-alpine
    environment:
      POSTGRES_DB: app
      POSTGRES_USER: app
      POSTGRES_PASSWORD: app
    volumes:
      - pg_data:/var/lib/postgresql/data
    healthcheck:
      test: pg_isready -U app -d app || exit 1
      interval: 5s
      start_period: 5s

  admin:
    image: docker.io/sosedoff/pgweb:0.14.0
    environment:
      PGWEB_DATABASE_URL: postgres://app:app@db/app?sslmode=disable
    ports:
      - 8081:8081
    depends_on:
      db:
        condition: service_healthy

  pooler:
    image: docker.io/bitnami/pgbouncer:1.18.0
    environment:
      POSTGRESQL_HOST: db
      POSTGRESQL_USERNAME: app
      POSTGRESQL_PASSWORD: app
      POSTGRESQL_DATABASE: app
      PGBOUNCER_DATABASE: app
    depends_on:
      db:
        condition: service_healthy

  client:
    image: docker.io/postgres:15.2-alpine
    environment:
      DATABASE_URL: postgres://app:app@pooler:6432/app
    depends_on:
      - pooler
    command:
      - /bin/sh
      - -c
      - "trap : TERM INT; sleep infinity & wait"

volumes:
  pg_data:
